backend:
  name: github
  repo: jonurace/prime
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: "proyectos"
    label: "Proyectos"
    folder: "content/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - name: "date"
        label: "Fecha"
        widget: datetime
      - name: "body"
        label: "Contenido"
        widget: "markdown"

  - name: "personas"
    label: "Personas"
    folder: "content/personas"
    create: true
    fields:
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Descripción", name: "body", widget: "markdown"}
